logging:
  level:
    root: info

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
